# Generated by Django 5.2.4 on 2025-07-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='contraseña',
            field=models.CharField(default=1234, max_length=50),
            preserve_default=False,
        ),
    ]
