# Generated by Django 5.2.4 on 2025-07-08 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuarios_contraseña'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='contraseña',
            new_name='contrasena',
        ),
    ]
